In [22]:
import numpy as np

In [80]:
numere = np.loadtxt('numbers.txt', delimiter=',') 
print('Numerele din fisier sunt: ',numere)

Numerele din fisier sunt:  [[10. 15. 20. 30.]
 [20. 25. 50. 80.]
 [50. 54. 55. 70.]
 [30. 35. 60. 13.]
 [40. 45. 70. 30.]
 [60. 66. 12. 17.]]


In [79]:
sumele=[line.sum() for line in numere] #ex1
print('Sumele corespunzatoare liniilor sunt: ',sumele)

Sumele corespunzatoare liniilor sunt:  [75.0, 175.0, 229.0, 138.0, 185.0, 155.0]


In [78]:
from functools import reduce #ex2
TotalSum= reduce(lambda x,y: x+y, sumele)
print('Suma tuturor numerelor din lista este: ', TotalSum)

Suma tuturor numerelor din lista este:  957.0


In [76]:
concat=[] #ex3
for line in numere:
    concat=[np.append(concat,line)]
print('Lista concatenata are forma: ',concat)

Lista concatenata are forma:  [array([10., 15., 20., 30., 20., 25., 50., 80., 50., 54., 55., 70., 30.,
       35., 60., 13., 40., 45., 70., 30., 60., 66., 12., 17.])]


In [82]:
k=0
for line in numere: #ex4
    for i in line:
        if (i>=30.1):
            k=k+1
print('Am gasit ',k,'numere in lista >=30.1!!!')

Am gasit  13 numere in lista >=30.1!!!


In [83]:
for s in range(1, 100+1):
    for j in range(1,len(concat)+1): #ex5
        lista=concat[j-1]<s
        print('Pentru pragul natural ',s,'avem', np.count_nonzero(lista),'numere din lista mai mici decat el!')

Pentru pragul natural  1 avem 0 numere din lista mai mici decat el!
Pentru pragul natural  2 avem 0 numere din lista mai mici decat el!
Pentru pragul natural  3 avem 0 numere din lista mai mici decat el!
Pentru pragul natural  4 avem 0 numere din lista mai mici decat el!
Pentru pragul natural  5 avem 0 numere din lista mai mici decat el!
Pentru pragul natural  6 avem 0 numere din lista mai mici decat el!
Pentru pragul natural  7 avem 0 numere din lista mai mici decat el!
Pentru pragul natural  8 avem 0 numere din lista mai mici decat el!
Pentru pragul natural  9 avem 0 numere din lista mai mici decat el!
Pentru pragul natural  10 avem 0 numere din lista mai mici decat el!
Pentru pragul natural  11 avem 1 numere din lista mai mici decat el!
Pentru pragul natural  12 avem 1 numere din lista mai mici decat el!
Pentru pragul natural  13 avem 2 numere din lista mai mici decat el!
Pentru pragul natural  14 avem 3 numere din lista mai mici decat el!
Pentru pragul natural  15 avem 3 numere din